pyd/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [

    path('about/', include("about.urls"), name="about-urls"),
    path("accounts/", include("allauth.urls")),
    path('admin/', admin.site.urls),
    path('summernote/', include('django_summernote.urls')),
    path('', include("tasks.urls"), name='tasks-urls'),

]

tasks/urls.py
from django.urls import path
from . import views

urlpatterns = [


     path('', views.home_view, name='home'),
     path('tasks/', views.task_listing, name='tasks'),

     path('view-date/', views.tasks_date_view, name='tasks_date_view'),

     path('statistics/', views.task_statistics, name='view_task_statistics'),

     path('view-date/edit_task/<int:task_id>', views.task_edit,
          name='tasks_edit'),
     path('view-date/delete_task/<int:task_id>',
          views.task_delete, name='task_delete'),

     path('<str:view_date>/edit_task/<int:task_id>',
          views.task_edit_with_date, name='tasks_edit_width_date'),

     path('<str:view_date>/delete_task/<int:task_id>',
          views.task_delete_with_date, name='task_delete_with_date'),
     path('view-date/<str:view_date>/delete_task/<int:task_id>',
          views.task_delete_with_date, name='task_delete_with_date'),

     path('add_task/<str:foo>/', views.add_task, name='add_task'),

     path('edit_task/<int:task_id>', views.task_edit, name='tasks_edit'),
     path('delete_task/<int:task_id>',
          views.task_delete, name='task_delete'),

     path('categories/', views.categories_listing, name='categories'),
     path('category/', views.category_listing, name='category'),
     path('add_category/<str:foo>/', views.add_category, name='add_category'),

     path('categories/edit_category/<int:category_id>',
          views.category_edit, name='category_edit'),

     path('categories/delete_category/<int:category_id>',
          views.category_delete, name='category_delete'),

     path('<str:view_date>/', views.home_view2, name='home2'),

]

tasks/models.py
from django.db import models
from django.contrib.auth.models import User
from django.contrib.auth.models import UserManager


def randomString():
    """This function is used to set a random string
    to the slug
    """
    um = UserManager()
    return (um.make_random_password(length=25))


# Create your models here.
class Category(models.Model):
    """This is the model for the Category

    Args:
        models (models.Model): The model to be
        used in the database

    Returns:
        category_name: return the category_name
    """
    category_name = models.CharField(max_length=25)
    author = models.ForeignKey(User, on_delete=models.CASCADE,
                               related_name="category_post")

    class Meta:
        ordering = ["category_name", "author"]

    def __str__(self):
        return f"{self.category_name}"


class Tasks(models.Model):
    """This si the task model for setting
    up the database

    Args:
        models (models.Model): the model to be used
        in the database

    Returns:
        task_name: returns the task_name of the Task
    """
    author = models.ForeignKey(
        User, on_delete=models.CASCADE, related_name="task_post"
    )
    task_name = models.CharField(max_length=50)
    task_description = models.TextField()
    is_urgent = models.BooleanField(default=False)
    date = models.DateField()
    start_time = models.TimeField()
    end_time = models.TimeField()
    category_id = models.ForeignKey(Category, on_delete=models.CASCADE,
                                    related_name="category")
    finished_task = models.BooleanField(default=False)

    class Meta:
        ordering = ["start_time", "author"]

    def __str__(self):
        return f"{self.task_name}"

tasks/forms.py
from datetime import date
from django import forms
from django.core.exceptions import ValidationError
from .models import Category, Tasks


class CategoriesForm(forms.ModelForm):
    """
    Allows a category form
    """

    def __init__(self, *args, **kwargs):
        """ Grants access to the request object so that only members of the
        current user
        are given as options"""
        # digout https://stackoverflow.com/questions/8841502/
        # how-to-use-the-request-in-a-modelform-in-django/8841565#8841565

        self.request = kwargs.pop('request')
        super(CategoriesForm, self).__init__(*args, **kwargs)
        self.fields['category_name'].queryset = Category.objects.filter(
            author=self.request.user)

    class Meta:
        model = Category
        fields = ('category_name',)


class DateInput(forms.DateInput):
    input_type = 'date'


class TasksForm(forms.ModelForm):
    """
    A tasks form

    Args:
        forms (forms.ModelForm): Allows the user an
        ability to add a task
    """

    def __init__(self, *args, **kwargs):
        """ Grants access to the request object so that only members of the
        current user
        are given as options"""
        # digout https://stackoverflow.com/questions/8841502/
        # how-to-use-the-request-in-a-modelform-in-django/8841565#8841565

        self.request = kwargs.pop('request')
        super(TasksForm, self).__init__(*args, **kwargs)
        self.fields['category_id'].queryset \
            = Category.objects.filter(author=self.request.user)

    class Meta:
        model = Tasks
        fields = ('category_id', 'task_name', 'task_description', 'is_urgent',
                  'date', 'start_time', 'end_time', 'finished_task')

        widgets = {
            'date': DateInput(),
            'start_time': forms.TimeInput(attrs={'type': 'time'}),
            'end_time': forms.TimeInput(attrs={'type': 'time'}),

        }

    def clean(self):
        cleaned_data = super().clean()
        start_time = cleaned_data.get('start_time')
        end_time = cleaned_data.get('end_time')

        if start_time >= end_time:
            raise ValidationError(
                 "The start time must be less than the end time!!")

        return self.cleaned_data


class TasksViewDate(forms.Form):
    """This form is used to set the date
    to view tasks by

    Args:
        forms (date): to set the date
    """
    today = date.today()
    date_to_view = forms.DateField(initial=today,
                                   required=True,
                                   widget=forms.DateInput(
                                    attrs={'type': 'date'}))


class TaskStatistics(forms.Form):
    """This form is used to display the statistics
    form to allow a logged in user access to stats

    Args:
        forms (date): the date from and date to fields
        are date typees and the category is the logged
        in users categories listing
    """

    def __init__(self, *args, **kwargs):
        """ Grants access to the request object so that only members of the
        current user
        are given as options"""
        # digout https://stackoverflow.com/questions/8841502/
        # how-to-use-the-request-in-a-modelform-in-django/8841565#8841565

        self.request = kwargs.pop('request')
        super(TaskStatistics, self).__init__(*args, **kwargs)
        self.fields['category_sel'].queryset = Category.objects.filter(
            author=self.request.user)

    def setUser(self):
        tUser = self.user

        return Category.objects.filter(user=tUser)

    today = date.today()
    date_from = forms.DateField(initial=today, required=True,
                                widget=forms.DateInput(attrs={'type': 'date'}))
    date_to = forms.DateField(initial=today, required=True,
                              widget=forms.DateInput(attrs={'type': 'date'}))

    category_sel = forms.ModelChoiceField(queryset=None)

tasks/views.py
import datetime
from datetime import datetime
from django.http import HttpResponseRedirect
from django.shortcuts import get_object_or_404, render
from django.shortcuts import redirect
from django.contrib import messages
from django.urls import reverse
from .models import Category, Tasks

from .forms import CategoriesForm, TasksForm, TasksViewDate, TaskStatistics


# Create your views here.
def home_view(request):
    """This function is used as the landing view
    of the website and displays a list of tasks
    based on logged in user and todays date.

    If the user is not logged in then a redirect
    is done to account_login

    Args:
        request (request.user.is_authenticated):
        checks to see if user ias logged in

    Returns:
        render: renders the index.html page
        if the user is authenticated
    """
    if not request.user.is_authenticated:
        return redirect(f"{'account_login'}")

    todays_date = datetime.now()

    tasks = Tasks.objects.filter(date__range=[todays_date, todays_date],
                                 author=request.user, finished_task=False)

    categories = Category.objects.filter(author=request.user)

    todays_date = todays_date.strftime("%a %B %d")

    context = {
        'date': todays_date,
        'tasks': tasks,
        "categories": categories,
    }

    return render(
        request,
        'tasks/index.html',
        context,
    )


def home_view2(request, view_date):
    """This function is used to display
    a list of tasks at a particular date

    Args:
        request (request.user): is used to
        get logged in user and to pass
        tasks based on it.
        view_date (string): This is the
        view_date wanted to display by.
        It will display tasks based on
        logged in user and view_date

    Returns:
        render: returns the context
        and page to render with the
        context infos.
    """

    tasks = Tasks.objects.filter(date__range=[view_date, view_date],
                                 author=request.user)

    categories = Category.objects.filter(author=request.user)

    view_date = datetime.strptime(view_date, "%Y-%m-%d").date()
    view_date_obj = view_date.strftime("%a %B %d")

    context = {
        'date': view_date_obj,
        'tasks': tasks,
        "categories": categories,
    }

    return render(
        request,
        'tasks/index.html',
        context,
    )


def categories_listing(request):
    """This view method is used to view
    the categories and to pass the categories
    to the categories.html template

    Args:
        request (request.user):used to get only
        the categories of the logged in user

    Returns:
        render: returns the categories to be viewed
        by the categories.html file
    """
    categories = Category.objects.filter(author=request.user)

    context = {
        "categories": categories,
    }
    return render(
        request,
        "tasks/categories.html",
        context,
    )


def category_listing(request):
    """passes the category_form to the
    add_category.html file

    Args:
        request (request.user):THe categories form
        requires that request.user be passed

    Returns:
        render: returns the category_form
        to the add_category.html template
    """

    category_form = CategoriesForm(request=request)

    return render(
        request,
        "tasks/add_category.html",
        {
            "category_form": category_form,
        },
    )


def task_listing(request):
    """passes the TasksForm and tasks
    to the add_task.html template

    Args:
        request (request.user): used to authenticate
        and display the form with only categories
        for the logged in  user

    Returns:
        render: returns tasks and the task_form
        to the add_task.html template
    """
    tasks = Tasks.objects.filter(author=request.user)

    task_form = TasksForm(request=request)

    return render(
        request,
        "tasks/add_task.html",
        {
            "tasks": tasks,
            "task_form": task_form,
        },
    )


def add_category(request, foo):
    """This function if the request method is
    a POST if the form is valid saves the form
    and creates a new category

    Args:
        request (data, request): the data and request
        information is required for this form
        foo (string): This was used to single out
        a url to add the category

    Returns:
        render: category_form to add_category.html
        template
    """
    category_form = None
    if request.method == "POST":
        category_form = CategoriesForm(data=request.POST, request=request)
        if category_form.is_valid():
            new_cat = None
            new_cat = category_form.save(commit=False)
            new_cat.author = request.user
            new_cat.save()
            messages.add_message(
                request, messages.SUCCESS,
                'Category submitted'
            )

    return HttpResponseRedirect(reverse('categories'))


def add_task(request, foo):
    """This function adds a task to the tasks list

    Args:
        request (data, request.user): the request.user
        is used to get the categories and to display only
        valid ones for the logged in user
        foo (string): This value was used to single out
        this url in the urls list

    Returns:
        render: task_form to add_task.html if error
        or redirect to home2 or home depending on the date
        for task listing
    """
    task_form = None
    if request.method == "POST":
        task_form = TasksForm(data=request.POST, request=request)
        if task_form.is_valid():
            new_task = None
            new_task = task_form.save(commit=False)
            new_task.author = request.user
            new_task.save()
            messages.add_message(
                request, messages.SUCCESS,
                'task submitted'
            )
        else:
            print(task_form.errors)
            messages.add_message(request, messages.ERROR,
                                 'Error adding task!')

            task_form = TasksForm(data=request.POST, request=request)

            return render(
                request,
                "tasks/add_task.html",
                {
                    "task_form": task_form,
                },
            )

    date_from = request.POST.get('date')

    view_date = date_from

    todays_date = datetime.now().date()
    todays_date = todays_date.strftime("%Y-%m-%d")

    if view_date == todays_date:
        return redirect(reverse('home'))
    else:
        return redirect(reverse('home2', args=[date_from]))


def category_edit(request, category_id):
    """This method is used to edit a category

    Args:
        request (user,data): used to get the logged
        in user and to get the data to populate the
        form
        category_id (int): used to pass the category_id
        to this method

    Returns:
        HttpResponseRedirect: does a redirect to the
        categories listing
    """
    if request.method == "POST":

        category = get_object_or_404(Category, pk=category_id)
        category_form = CategoriesForm(data=request.POST, instance=category,
                                       request=request)

        if category_form.is_valid() and category.author == request.user:
            category = category_form.save(commit=False)
            category.approved = False
            category.save()
            messages.add_message(request, messages.SUCCESS,
                                 'Category Updated!')
        else:
            messages.add_message(request, messages.ERROR,
                                 'Error updating category!')

    return HttpResponseRedirect(reverse('categories'))


def task_edit(request, task_id):
    """used to edit a task

    Args:
        request (user,data): used to authenticate the user
        and to get the data to edit to populate the form
        task_id (int): used to get the task_id of the
        database table entry to be edited

    Returns:
        _type_: _description_
    """
    if request.method == "POST":

        task = get_object_or_404(Tasks, pk=task_id)
        task_form = TasksForm(data=request.POST, instance=task,
                              request=request)

        if task_form.is_valid() and task.author == request.user:
            new_task = task_form.save(commit=False)

            new_task.save()
            messages.add_message(request, messages.SUCCESS, 'Task Updated!')
        else:
            messages.add_message(request, messages.ERROR,
                                 'Error updating task!')

    date_from = request.POST.get('date')

    view_date = date_from
    todays_date = datetime.now().date()
    todays_date = todays_date.strftime("%Y-%m-%d")

    if view_date == todays_date:
        return redirect(reverse('home'))
    else:
        return redirect(reverse('home2', args=[date_from]))


def task_edit_with_date(request, view_date, task_id):
    """This function allows an edit of a task with the
    view_date in the url

    Args:
        request (data, request): The task form requires
        the data and instance and request = request.user
        in order to validate the categories listing for
        the logged in user
        view_date (string): This value is used to pass
        the view_date to the home2 view for listing
        task_id (int): used to uniquely identify the
        task to be edited

    Returns:
        redirect: to home2 given date_from
    """
    if request.method == "POST":

        task = get_object_or_404(Tasks, pk=task_id)
        task_form = TasksForm(data=request.POST, instance=task,
                              request=request)

        if task_form.is_valid() and task.author == request.user:
            new_task = task_form.save(commit=False)

tasks/templates/tasks/add_category.html
{% extends 'base.html' %}
{% block content %}
{% load static %}
{% load crispy_forms_tags %}

<div class="container">

<!-- Creating New Categories -->
    <div class="col-md-4 card mb-4 mt-3">
        <div class="card-body">
            {% if user.is_authenticated %}
            <h3>Add new Category:</h3>
            <p>Posting as: {{ user.username }}</p>
            <form id="categoryForm" method="POST" action="{% url 'add_category' 'category_form.POST.category_name' %}"
                style="margin-top: 1.3em;">
                {{ category_form | crispy }}
                {% csrf_token %}
                <button id="submitButton" type="submit"
                class="btn btn-signup btn-lg">Submit</button>
            </form>
            {% else %}
            <p>Log in to use system!!</p>
            {% endif %}
        </div>

    </div>
</div>
{% endblock content %}
{% block copyright %}
    CopyRight 2023 Michael Cloran
{% endblock %}

tasks/templates/tasks/add_task.html
{% extends 'base.html' %}
{% block content %}
{% load static %}
{% load crispy_forms_tags %}

<div class="container">

<!-- Creating New Categories -->
    <div class="col-md-4 card mb-4 mt-3">
        <div class="card-body">
            {% if user.is_authenticated %}
            <h3>Add new Category:</h3>
            <p>Posting as: {{ user.username }}</p>
            <form id="taskForm" method="POST" action="{% url 'add_task' 'task_form.POST.task_name' %}"
                style="margin-top: 1.3em;">
                {{ task_form | crispy }}
                {% csrf_token %}
                <button id="submitButton" type="submit"
                class="btn btn-signup btn-lg">Submit</button>
            </form>
            {% else %}
            <p>Log in to use system</p>
            {% endif %}
        </div>

    </div>
</div>
{% endblock content %}
{% block copyright %}
    CopyRight 2023 Michael Cloran
{% endblock %}

tasks/templates/tasks/index.html
{% extends "base.html" %}
{% load static %}

{% block content %}

{% load crispy_forms_tags %}

<!-- index.html content starts here -->
{% if user.is_authenticated %}
<div class="container-fluid">
  <a href="{% url 'tasks' %}" class="btn btn-outline-primary right d-flex justify-content-center align-content-center" ><span style="color:rgb(2, 51, 126);">Add Task</span></a>
  <input type='button' name="show-docs" id='show-docs' value="Documentation">
  <div class="row">
        <!-- Task Entries Column -->
        <div class="col-12">
          <h3 class="align-middle d-flex justify-content-center align-content-center">Tasks: {{date}}</h3>
          {% if tasks|length > 0 %}
          <div class="accordion" id="accordionTasks">
                {% for task in tasks %}

                {% if user == task.author %}

                <div class="accordion-item">
                  <h2 class="accordion-header">
                    <button class="accordion-button" type="button" data-bs-toggle="collapse" data-bs-target="#accordion{{task.id}}" aria-expanded="true" aria-controls="accordion{{task.id}}">
                      <strong>{{ task.task_name }}: &nbsp;</strong>
                      <strong> Start:&nbsp; </strong>{{task.start_time|date:"H:i"}}
                      <strong> &nbsp; End: &nbsp; </strong>{{ task.end_time|date:"H:i"}}
                      {% if task.is_urgent == True %}
                        <strong class='urgent-task'>&nbsp; &nbsp; URGENT</strong>
                      {% endif %}
                      {% if task.finished_task == True %}
                        <strong class='finished-task' style='color:green;'>&nbsp; &nbsp; Finished</strong>
                      {% endif %}
                    </button>
                  </h2>
                  <div id="accordion{{task.id}}" class="accordion-collapse collapse" data-bs-parent="#accordionTasks">
                    <div class="accordion-body">

                      <div class="row d-flex justify-content-center align-content-center">
                        <div class="col-md-4">
                            <div class="card mb-4">
                                <div class="card-body task-container">
                                    <div class="image-container">

                                        <div class="image-flash">
                                          <p class="author">Author: {{ task.author }}</p>
                                        </div>
                                    </div>
                                      <div>
                                        <h2 class="card-title task-name">{{ task.task_name }}</h2>
                                        <p class="crd-text task-description">
                                          {{ task.task_description }}
                                        </p>
                                        <p class="srd-text task-misc">
                                          <span class="task-date">{{task.date|date:"Y-m-d"}}</span> Category:<strong class="task-category">{{task.category_id}}</strong>
                                        </p>
                                        <p class="srd-text task-start-end-time">
                                          start time <span class="task-start">{{task.start_time|date:"H:i"}}</span>
                                          end time <span class="task-end">{{ task.end_time|date:"H:i"}}</span>
                                        </p>

                                        <button class="btn btn-delete btn-delete-task"
                                            data-task_id="{{ task.id }}">Delete</button>
                                        <button class="btn btn-edit btn-edit-task"
                                            data-task_id="{{ task.id }}">Edit</button>

                                        <hr>
                                      </div>
                                </div>
                            </div>
                        </div>
                      </div>
                    </div>
                  </div>
                </div>
                {% endif %}

                {% endfor %}
              </div><!-- accordion-->
            {% else %}
            <div class="row d-flex justify-content-center align-content-center">
              <div class="col-md-4">
                <div class="card mb-4">
                  <h2>No tasks for today</h2>
                </div>
              </div>
            </div>
            {% endif %}
            <div class="row">
            </div>
        </div>
    </div>

</div>
<!-- update tasks modal-->
<div class="modal" id="editTaskModal" tabindex="-1" role="dialog">
    <div class="modal-dialog" role="document">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title">Update Task</h5>
          <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>

        <form name="editTaskForm" method="POST" class="was-validated">
        <div class="modal-body">

            <label for="id_category_id" class="form-label requiredField"> Category id<span class="asteriskField">*</span></label>
            <select name="category_id" class="select form-select" required size="1" id="id_category_id">
                <option value="">Choose</option>
                {% for category in categories %}
                {% if category.author == user %}
                <option value="{{category.id}}">{{category.category_name}}</option>
                {% endif %}
                {% endfor %}
            </select>

            <div class="mb-3 mt-3">
              <label for="id_task_name" class="form-label requiredField">Task name<span class="asteriskField">*</span></label>
              <input type="text" name="task_name" maxlength="50" class="textinput form-control" required id="id_task_name">
              <div class="valid-feedback">Vaild.</div>
              <div class="invalid-feedback">
                Please provide a valid task name.
              </div>
            </div>

            <div class="mb-3">
              <label for="id_task_description" class="form-label requiredField">Task description<span class="asteriskField">*</span></label>
              <textarea name="task_description" cols="40" rows="10" class="textarea form-control" required id="id_task_description"></textarea>
              <div class="valid-feedback">Vaild.</div>
              <div class="invalid-feedback">
                Please provide a valid text.
              </div>
            </div>

            <input type="checkbox" name="is_urgent" class="checkboxinput form-check-input" id="id_is_urgent">
            <label for="id_is_urgent" class="form-check-label">
                Is urgent
            </label><br>

            <div class="mb-3">
              <label for="id_date" class="form-label requiredField">
                  Date<span class="asteriskField">*</span> </label>
              <input type="date" name="date" class="dateinput form-control" required id="id_date">
              <div class="valid-feedback">Vaild.</div>
              <div class="invalid-feedback">
                Please provide a valid date.
              </div>
            </div>

            <div class="mb-3">
              <label for="id_start_time" class="form-label requiredField">
                  Start time<span class="asteriskField">*</span> </label><input type="button" id="start_time_ck" value="Set to current time">
              <input type="time" name="start_time" class="timeinput form-control" required id="id_start_time">
              <div class="valid-feedback">Vaild.</div>
              <div class="invalid-feedback">
                Please provide a valid start time hh:mm.
              </div>
            </div>

            <div class="mb-3">
              <label for="id_end_time" class="form-label requiredField">
                  End time<span class="asteriskField">*</span></label><input type="button" id="end_time_ck" value="Set to current time">
              <input type="time" name="end_time" class="timeinput form-control" required id="id_end_time">
              <div class="valid-feedback">Vaild.</div>
              <div class="invalid-feedback">
                Please provide a valid end time hh:mm.
              </div>
            </div>

            <div id="div_id_finished_task" class="mb-3 form-check">
              <input type="checkbox" name="finished_task" class="checkboxinput form-check-input" id="id_finished_task">
              <label for="id_finished_task" class="form-check-label">Finished task</label>
            </div>
            {% csrf_token %}

        </div>
        <div class="modal-footer">
          <button type="button" id="cancel" name="cancel" class="btn btn-secondary" data-dismiss="modal">Cancel</button>
          <button type="button" id="update" name="update" class="btn btn-primary">Update</button>
        </div>
      </form>

      </div>
    </div>
  </div>
  <!-- docs modal-->
  <div class="modal" tabindex="-1" id="documentation-modal">
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title">System Documentation</h5>
          <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
        </div>
        <div class="modal-body">
          <h2>Welcome, this is some basic documentation for the system</h2>
          <p>In order to use the system you have to create categories (click on the categories nav-bar item and add category)
            Then once categories are created you can click on the home nav-bar item to view todays tasks and to add a task
            just click on the add task button. Or you can view a particular date by clicking on the view date nav-bar item.</p>

            <p>It is possible with this system to view statistics by clicking on the statistics nav-bar item and choosing a from
              and to date and then choosing a category. The stats are run through all tasks under a category and the time
              within the time frame is totted up and displayed in a table</p>
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
        </div>
      </div>
    </div>
  </div>

  <!-- Delete confirmation modal -->
<div class="modal fade" id="deleteTaskModal" tabindex="-1"
aria-labelledby="deleteModalLabel" aria-hidden="true">
<div class="modal-dialog">
  <div class="modal-content">
    <div class="modal-header">
      <h5 class="modal-title"
        id="deleteModalLabel">Delete task?</h5>
      <button type="button" class="btn-close"
        data-bs-dismiss="modal" aria-label="Close"></button>
    </div>
    <div class="modal-body">
      Are you sure you want to delete your task?
      This action cannot be undone.
    </div>
    <div class="modal-footer">
      <button type="button" class="btn btn-secondary"
        data-bs-dismiss="modal">Close</button>
      <a id="deleteTaskConfirm" href="#" class="btn
        btn-danger">Delete</a>
    </div>
  </div>
</div>
</div>

<script type="text/javascript">
document.getElementById("show-docs").addEventListener('click', () => {
  const docs_modal = new bootstrap.Modal( document.getElementById("documentation-modal"));
  docs_modal.show();

});
</script>
{% endif %}
<!-- index.html content ends here -->
{% endblock %}
{% block copyright %}
    CopyRight 2023 Michael Cloran
{% endblock %}
{% block extras %}
<script src="{% static 'js/tasks.js' %}"></script>
{% endblock %}